image:
  file: .gitpod.Dockerfile
tasks:
  - command: redis-server
  - before: cp ./init-localstack.sh /docker-entrypoint-initaws.d/init-localstack.sh
    init: pip install --quiet localstack[full]
    command: /workspace/.pip-modules/bin/localstack start --host
  - before: export ACCESS_ENDPOINT=`gp url 4566`
    init: npm install
    command: /tmp/wait-for-it.sh localhost:4566 -t 0 -- ./init-localstack.sh && echo "Run npm run docker-dev to begin"
  - init: npm install maildev -g
    command: maildev --verbose
ports:
  # postgres
  - port: 5432
    onOpen: ignore
  # redis
  - port: 6379
    onOpen: ignore
  # localstack
  - port: 4566
    onOpen: ignore
  - port: 4572
    onOpen: ignore
  - port: 9229
    onOpen: ignore
  # expressjs - not needed since we have
  # access via webpack dev server proxy
  - port: 8080
    onOpen: ignore
  # maildev
  - port: 1025
    onOpen: ignore
