FROM node:14-alpine3.12

LABEL maintainer="Open Government Products" email="go@open.gov.sg"

ARG BUILD_MODE

WORKDIR /usr/src/gogovsg

# For Express server
EXPOSE 8080

# For dev webpack server only, proxies to localhost:8080
EXPOSE 3000

RUN apk update && apk add ttf-freefont && rm -rf /var/cache/apk/*

# Install libraries
COPY package.json package-lock.json ./

RUN npm ci

COPY . ./
