name: ci
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
      - run: npx lockfile-lint --type npm --path package-lock.json --validate-https --allowed-hosts npm
      - run: npm run build
        env:
          ASSET_VARIANT: gov

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci --legacy-peer-deps
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: gogovsg
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm run test
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}

  testcafe:
    name: End To End Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci --legacy-peer-deps
      - run: echo CLOUDMERSIVE_KEY=${{secrets.CLOUDMERSIVE_KEY}} >> .env
      - run: npm run docker:build
      - run: npm run docker:up
      - run: sleep 270
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: gogovsg
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm run test:e2e-headless
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}

  integration:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci --legacy-peer-deps
      - run: npm run docker:build
      - run: npm run docker:up
      - run: sleep 270
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: gogovsg
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm run test:integration
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
