name: ci
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run lint

  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run format:check

  typecheck:
    name: Typecheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run typecheck

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run build
        env:
          ASSET_VARIANT: gov
      - run: npx lockfile-lint --type npm --path package-lock.json --validate-https --allowed-hosts npm

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: gogovsg
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm run test
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}

  testcafe:
    name: End To End Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: echo CLOUDMERSIVE_KEY=${{secrets.CLOUDMERSIVE_KEY}} >> .env
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: gogovsg
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm run test:e2e-headless
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}

  integration:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run dev &
      - run: sleep 270
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: gogovsg
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm run test:integration
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
